services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-mydatabase}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}'
      - 'POSTGRES_USER=${POSTGRES_USER:-myuser}'
    ports:
      - '5432:5432'
